// Jobs, research positions and community work, each list in display order (oldest first).
// Fields:
//   id, employer, role, type, start, end ("YYYY-MM" or null), place, mode
//   aboutLabel, aboutUrl   the linked name printed first in the About block
//   about                  the text after the name in the About block. A string, or an array of
//                          segments (a segment is a plain string or { text, href } for a link)
//   description            one or two sentences for skins that show details
//   bullets                the strongest facts, one short sentence each
//   roles                  optional list of { title, start, end, place } when one employer had several roles
export const industry = [
  {
    id: "amazon",
    employer: "Amazon",
    role: "Operations Intern",
    type: "Internship",
    start: "2023-06",
    end: "2023-08",
    place: "Salem, Oregon",
    mode: "On-site",
    description: "Built an internal TypeScript, React and Node.js tool for Inbound Operations that optimized drop zones and cut onboarding, research and lost-inventory costs.",
    bullets: [
      "Cut onboarding costs by more than $10k, a 95% reduction.",
      "Wrote sustainable standard work procedures.",
      "Had multiple white papers approved by senior managers and the site director.",
      "Was deputized as a Loss Prevention Officer.",
    ],
    aboutLabel: "Amazon",
    aboutUrl: "https://www.amazon.com/",
    about: "Operations Intern, Jun 2023 - Aug 2023",
  },
  {
    id: "prosperon",
    employer: "ProsperOn",
    role: "Website Developer",
    type: "Internship",
    start: "2023-06",
    end: "2024-02",
    place: "Boston, Massachusetts",
    mode: "Remote",
    description: "Built financial simulation web pages in TypeScript and React and took over legacy code from earlier developers.",
    bullets: [
      "Implemented a variety of financial simulation pages.",
      "Updated legacy code from previous developers.",
      "Integrated the front end and back end through RESTful APIs.",
    ],
    aboutLabel: "ProsperOn",
    about: "Website Developer, Jun 2023 - Feb 2024",
  },
  {
    id: "enlabel",
    employer: "enLabel Global Services, Inc.",
    role: "Full-Stack Software Engineer",
    type: "Full-time",
    start: "2024-01",
    end: "2025-01",
    place: "North End, Boston",
    mode: "On-site",
    description: "Led the technical direction of modular, adaptable products with a React and TypeScript front end over an ASP.NET API.",
    bullets: [
      "Designed a modular codebase that adapts quickly to branding and localization needs.",
      "Wrote the technical documentation for maintenance and knowledge transfer.",
      "Resolved 50+ bugs and tickets in legacy code with little documentation.",
    ],
    aboutLabel: "enLabel",
    aboutUrl: "https://www.enlabel.com/",
    about: "Full-Stack Software Engineer, Jan 2024 - Jan 2025",
  },
  {
    id: "cyvl",
    employer: "Cyvl",
    role: "Full-Stack Software Engineer",
    type: "Full-time",
    start: "2025-08",
    end: "2026-08",
    place: "Somerville, Massachusetts",
    mode: "On-site",
    description: "Built and extended production pipelines that turn petabyte-scale LiDAR and street-level imagery into digital twins of municipal infrastructure.",
    bullets: [
      "Designed the AI ingestion pipeline that turns municipal engineering documents into geospatial files. It won NYC DEP's Environmental Technology Lab Challenge.",
      "Built a visual embedding pipeline over 500k+ street-level images per city for sub-second semantic retrieval.",
      "Extended pipelines that find pavement distress, signs, markings and above-ground assets.",
      "Built Model Context Protocol servers with City of Boston leadership for natural-language access to infrastructure data.",
      "An internal assignment on calibrated confidence scoring grew into my doctoral research.",
    ],
    aboutLabel: "CYVL",
    aboutUrl: "https://www.cyvl.com/",
    about: "Full-Stack Software Engineer, Aug 2025 - Aug 2026",
  },
];

export const research = [
  {
    id: "tufts-hilab",
    employer: "Tufts University",
    role: "Graduate Research Assistant, Human Interaction Lab",
    type: "Research",
    start: "2025-01",
    end: "2025-05",
    place: "Medford, Massachusetts",
    mode: "Hybrid",
    description: "Became lead engineer of the back-end team for GailBot, a transcription pipeline for conversation analysis.",
    bullets: [
      "Contributed to a Docker-based, plugin-driven pipeline for paralinguistic annotation.",
      "Built cross-platform back-end APIs and macOS and Linux installers.",
      "Cut transcription and analysis times by more than 10 minutes by trimming plugin dependencies.",
      "Wrote the documentation and led end-to-end testing.",
    ],
    aboutLabel: "Tufts",
    aboutUrl: "https://www.tufts.edu/",
    about: [{ text: "Human Interaction Laboratory", href: "https://sites.tufts.edu/hilab/" }, ", Jan - May 2025"],
  },
  {
    id: "afrl",
    employer: "Air Force Research Laboratory",
    role: "Swarm Robotics AI Research Intern",
    type: "Internship",
    start: "2025-05",
    end: "2025-08",
    place: "Eglin Air Force Base, Florida",
    mode: "On-site",
    description: "Developed heterogeneous multi-agent reinforcement learning algorithms for swarm systems.",
    aboutLabel: "USRA",
    aboutUrl: "https://www.usra.edu/",
    about: [{ text: "Air Force Research Laboratory", href: "https://www.afrl.af.mil/" }, ", May - Aug 2025"],
  },
  {
    id: "wpi-aifc",
    employer: "Worcester Polytechnic Institute",
    role: "Research Intern, AI Futures Collab",
    type: "Internship",
    start: "2025-05",
    end: "2025-09",
    place: "Worcester, Massachusetts",
    mode: "Remote",
    description: "Worked with Dr. Yunus Telliel on human and AI interfacing and literacy, the ethics of AI-driven media, and how faculty adopt AI in higher education.",
    aboutLabel: "WPI",
    aboutUrl: "https://www.wpi.edu/",
    about: "AI Futures Collab, May - Sep 2025",
  },
  {
    id: "nyu-fellow",
    employer: "NYU Tandon School of Engineering",
    role: "School of Engineering Fellow",
    type: "Full-time",
    start: "2026-08",
    end: null,
    place: "Brooklyn, New York",
    mode: "On-site",
    description: "Researching in the Urban Modeling Group, advised by Dr. Debra Laefer. Thesis: Understand, Standardize, Mitigate: Uncertainty in 3D Models of Urban Environments for Autonomous Decision-Making. Presented at IROS: Full-Shift Robot Co-Workers 2026.",
    aboutLabel: "NYU",
    aboutUrl: "https://www.nyu.edu/",
    about: [{ text: "Urban Modeling Group", href: "https://wp.nyu.edu/urbanmodeling/" }, ", Aug 2026 - present"],
  },
];

export const community = [
  {
    id: "ywca",
    employer: "YWCA Central Massachusetts",
    role: "Lifeguard, Gym Instructor and Swim Instructor",
    type: "Part-time",
    start: "2021-08",
    end: "2022-06",
    place: "Worcester, Massachusetts",
    roles: [
      { title: "Lifeguard", start: "2021-08", end: "2022-06", place: "Worcester, Massachusetts" },
      { title: "Swim Instructor", start: "2021-09", end: "2022-06" },
      { title: "Gym Instructor", start: "2021-12", end: "2022-06", place: "Worcester, Massachusetts" },
    ],
    description: "Guarded open-swim and lesson hours at a community pool and performed three lifesaving interventions.",
    aboutLabel: "YWCA",
    aboutUrl: "https://ywcacm.org/",
    about: "Lifeguard, Swim and Gym Instructor, Aug 2021 - Jun 2022",
  },
  {
    id: "untitled",
    employer: "Untitled LLC",
    role: "Co-Founder and Chief Logistics Officer",
    type: "Self-employed",
    start: "2023-12",
    end: "2026-05",
    place: "Boston, Massachusetts",
    mode: "On-site",
    description: "Co-founded an underground arts collective that secured venues, sponsors and studio space and produced sold-out fashion shows and performances.",
    bullets: [
      "Managed cross-functional teams and handled legal and financial strategy.",
      "Coordinated security and harm reduction and raised funds for underrepresented artists.",
      "Inducted into the Honos Civicus Society for the work.",
    ],
    aboutLabel: "Untitled",
    aboutUrl: "https://untitled.boston/",
    about: "Co-Founder, Dec 2023 - May 2026",
  },
  {
    id: "cyvl-community",
    employer: "Cyvl",
    role: "Community Team Coordinator",
    type: "Community",
    start: "2025-09",
    end: "2026-08",
    place: "Somerville, Massachusetts",
    description: "Taught the Infrastructure Intelligence sessions of the Public Innovation Institute and Cyvl Summer Innovation Program and built outreach to university and data communities.",
    aboutLabel: "CYVL",
    aboutUrl: "https://www.cyvl.com/",
    about: "Community Team Coordinator, Sep 2025 - Aug 2026",
  },
];
