// Every project card, in display order inside its track.
// Fields:
//   id, title
//   track         "academic" (course, lab and research work) or "misc" (everything else)
//   image         a key of `images` in src/assets/index.js
//   link          where the card and its title point
//   text          the short card text, one or two sentences. The card box is fixed height, so keep it short.
//   dates, organization, course, contributors, tags   optional extras for skins that show more
//   long          the full description for skins with room for it
//   publicationId optional id in publications.js when a paper covers the same work
const LINKEDIN = "https://www.linkedin.com/in/phi-bui/";

export const projects = [
  {
    id: "human-interaction-lab-gailbot",
    title: "Human Interaction Lab: GailBot",
    track: "academic",
    image: "hilab",
    link: "https://www.gailbot.ai/",
    text: "PyPI-distributed transcription pipeline for conversation analysis. I led its back-end overhaul.",
    dates: "Jan 2025 - May 2025",
    organization: "Tufts University",
    tags: ["Python", "Docker", "REST", "PostgreSQL", "React"],
    publicationId: "gailbot-icca",
    long: "GailBot adds Jeffersonian annotations for silences, overlaps, speech rate and laughter to speech-to-text transcripts. It uses a Docker-based plugin pipeline, cross-platform APIs and a CLI so researchers can build and deploy their own analysis modules. I became lead engineer of the back-end team.",
  },
  {
    id: "llms-can-be-judgy-too",
    title: "LLMs Can Be Judgy Too",
    track: "academic",
    image: "tufts",
    link: "https://www.are.na/block/36403350",
    text: "Fine‑tuned LLMs can proxy human reward in PPO for facial expression RL, boosting accuracy and reducing labeling vs pure human feedback.",
    dates: "Dec 2024 - May 2025",
    organization: "Tufts University",
    course: "CS 138: Reinforcement Learning",
    tags: ["PPO", "LLM", "reward modeling"],
    long: "A PPO framework that uses a fine-tuned LLM as a proxy human reward to guide an agent in generating facial Action Unit expressions for narrative characters. We compared human feedback only, LLM reward only and a hybrid under a fixed feedback budget, and evaluated them on 30 narrative situations with a blinded survey of twelve participants.",
  },
  {
    id: "metrics-driven-safe-rl-for-ai-driving",
    title: "Metrics‑Driven Safe RL for AI Driving",
    track: "academic",
    image: "tufts",
    link: "https://www.are.na/block/36445938",
    text: "A non-learned supervisor that enforces safety norms on DQN agents in HighwayEnv, built for an ethics course. The improved version is the workshop paper listed under Publications and Presentations.",
    dates: "Jan 2025 - May 2025",
    organization: "Tufts University",
    course: "CS 239: Ethics for AI Robotics and HRI",
    contributors: ["Thomas Howell", "Robert McPherson"],
    tags: ["safe RL", "DQN", "HighwayEnv", "normative supervision"],
    publicationId: "scps-workshop",
    long: "A metrics-driven normative supervisor that augments a Deep Q-Network agent. It is a non-learned policy layer in HighwayEnv with quantitative norms for speeding, tailgating, sudden braking and safe lane changes, and it corrects unsafe actions at runtime. The paper is listed under Publications and Presentations.",
  },
  {
    id: "civic-honesty-benchmark",
    title: "Civic Honesty Benchmark",
    track: "academic",
    image: "hami",
    link: "https://github.com/phbui/civic-honesty-benchmark",
    text: "A live-data benchmark over a municipal open-data API. The dataset and episode logs are public. The paper is listed under Publications and Presentations.",
    dates: "2026",
    organization: "Independent research",
    tags: ["LLM evaluation", "open data", "benchmark"],
    publicationId: "civic-honesty",
  },
  {
    id: "caption-enrichment-for-neurodivergent-users",
    title: "Caption Enrichment for Neurodivergent Users",
    track: "academic",
    image: "tufts",
    link: "https://github.com/phbui/real-time-captioning-extension",
    text: "LLM-augmented captions add tone, intent, emotion cues to audio subtitles, improving comprehension, reducing cognitive load for neurodivergent users.",
    dates: "Jan 2025 - May 2025",
    organization: "Tufts University",
    course: "CS 150: Special Topics, HCI for Disability",
    contributors: ["Cheyanne", "Katharine"],
    tags: ["Mistral-7B", "WebSocket", "accessibility", "Chromium extension"],
    long: "A real-time video captioning extension that uses a quantized Mistral-7B model to enrich transcripts with tone, sentiment and intent over a low-latency WebSocket pipeline. We ran two pilot studies with eight university students and three neurodivergent participants.",
  },
  {
    id: "sphero-swarm-framework",
    title: "Sphero Swarm Framework",
    track: "academic",
    image: "tufts",
    link: "https://www.are.na/block/33345533",
    text: "A framework for Sphero swarm navigation using probabilistic methods and computer vision, developed for Tufts' human-robot interaction research.",
    dates: "Sep 2024 - Dec 2024",
    organization: "Tufts University",
    course: "CS 141: Probabilistic Robotics",
    tags: ["Monte Carlo Localization", "PRM", "computer vision", "swarms"],
    long: "A swarm navigation framework for Sphero Bolt robots. Monte Carlo Localization and Probabilistic Roadmaps use an overhead camera for real-time localization, mapping and obstacle detection, with feedback-driven trajectory adjustments for collision-free navigation on low-cost hardware.",
  },
  {
    id: "robot-system-investigations",
    title: "Robot System Investigations",
    track: "academic",
    image: "tufts",
    link: "https://www.are.na/block/33345530",
    text: "Explored human preferences in manual vs autonomous control of Sphero robots, emphasizing trust and adaptability in navigation systems.",
    dates: "Sep 2024 - Dec 2024",
    organization: "Tufts University",
    course: "CS 133: Human-Robot Interaction",
    contributors: ["Ju-Hung"],
    tags: ["HRI", "user study", "Sphero Bolt"],
    long: "A study built on the Sphero swarm framework. Participants navigated obstacle courses by hand or watched autonomous navigation, which shows how much users value trust and control.",
  },
  {
    id: "worcester-permitpro",
    title: "Worcester PermitPro",
    track: "academic",
    image: "wpi",
    link: "https://www.are.na/block/26865313",
    text: "An LLM-driven due-diligence and smart-contract platform for low-income housing in Worcester, built for WPI's Major Qualifying Project. The City of Worcester now operates it.",
    dates: "Aug 2023 - Dec 2023",
    organization: "Worcester Polytechnic Institute",
    course: "Major Qualifying Project",
    contributors: ["Hasan", "Jack", "6 others"],
    tags: ["GIS", "LLM", "blockchain", "PostgreSQL", "React"],
    long: "Built with the City of Worcester's Chief Development Officer to streamline land acquisition, zoning approval and financing for low-income housing. It joins GIS layers and open municipal data behind a real-time tracking interface and publishes records to a blockchain. A homeless shelter and rehabilitation clinic broke ground in record time as a result.",
  },
  {
    id: "nitrocycle",
    title: "NitroCycle",
    track: "academic",
    image: "wpi",
    link: "https://github.com/IQP-NCPOGD/nitrocycle",
    text: "An augmented reality game about nitrogen cycles in farming made for Boys & Girls Club for the WPI's Interactive Qualifying Project program.",
    dates: "Oct 2022 - Mar 2023",
    organization: "Worcester Polytechnic Institute",
    course: "Interactive Qualifying Project, with the Boys & Girls Club of Fitchburg and Leominster",
    contributors: ["Ethan", "Hasan", "3 others"],
    tags: ["AR", "game design", "product management"],
    long: "An incremental augmented reality game about nitrogen fixation, sponsored by the Boys and Girls Club and the WPI STEM Education Center. I was the product manager and designed the interface, gameplay and mechanics, and I built front-end features.",
  },
  {
    id: "ai-architecture-for-storytelling",
    title: "AI Architecture for Storytelling",
    track: "academic",
    image: "chatgpt",
    link: "https://www.are.na/block/33237601",
    text: "An AI-driven architecture for immersive storytelling, integrating procedural generation, large language models, and player behavior modeling.",
  },
  {
    id: "chatgpt-how-do-i-design",
    title: "ChatGPT, How Do I Design?",
    track: "academic",
    image: "chatgpt",
    link: "https://www.are.na/block/26865380",
    text: "This paper advocates for harmonious human-AI co-creation in creativity, acknowledging benefits, challenges, and ethics.",
    dates: "Mar 2023 - May 2023",
    organization: "Worcester Polytechnic Institute",
    course: "Humanities and Arts capstone, Love, Death, and Robots",
    contributors: ["Yunus Doğan"],
    tags: ["ethics", "generative AI", "design"],
    long: "A capstone paper titled How Do I Design? Integrating Modern Generative AI into the Design Process. It weighs the ethical, societal and creative challenges of co-creating with AI and argues for human oversight and multidisciplinary collaboration. Professor Yunus Telliel mentored the work.",
  },
  {
    id: "medical-service-request-system",
    title: "Medical Service Request System",
    track: "academic",
    image: "mgbwh",
    link: "https://github.com/phbui/BWH-Medical-Service-Request-System",
    text: "A medical service request system (MSRS) made for Brigham and Women's Hospital (BWH) during WPI's Software Engineering course.",
    dates: "Mar 2022 - Apr 2022",
    organization: "Worcester Polytechnic Institute",
    course: "CS3733: Software Engineering",
    contributors: ["Ethan", "Caleb", "6 others"],
    tags: ["Java", "Agile", "UML"],
    long: "An eleven-person team built a medical equipment tracking and workflow application with a hospital dashboard, a floor map editor and several service request modules. I wrote the front end and part of the back end, designed the special feature subsystems with UML diagrams and led the interactive visual simulation subgroup. We delivered it in eight weeks.",
  },
  {
    id: "untitled",
    title: "Untitled",
    track: "misc",
    image: "untitled",
    link: "https://untitled.boston/",
    text: "A website I made for Untitled LLC, the underground arts collective I co-founded in Boston, MA.",
  },
  {
    id: "tarot-cards",
    title: "Tarot Cards",
    track: "misc",
    image: "tarot",
    link: "https://objectivephi.github.io/",
    text: "A little tarot card reader I made on my downtime at work.",
  },
  {
    id: "main-era",
    title: "Main Era",
    track: "misc",
    image: "mainEra",
    link: "https://main-era.github.io/",
    text: "A website I made for a Boston-based, indie punk band.",
  },
  {
    id: "haven",
    title: "Haven",
    track: "misc",
    image: "tufts",
    link: "https://www.are.na/block/26865372",
    text: "A live map for anonymous incident reporting and resource location. It won 1st place in the Health/Wellness category at the Tufts Producthon Sprint 2024.",
    dates: "Feb 2024",
    organization: "Tufts University",
    course: "Tufts Producthon Sprint 2024",
    contributors: ["William", "Alice"],
    tags: ["hackathon", "maps", "harm reduction"],
    long: "A map that doubles as a harm reduction resource locator, for example where to get Narcan or Plan B, and a heatmap of anonymously reported incidents. It gives college students a safe way to warn their community and helps victims speak up.",
  },
  {
    id: "bu-barbell-collab",
    title: "BU Barbell x WPI Powerlifting",
    track: "misc",
    image: "wpi",
    link: LINKEDIN,
    text: "A collaborative lift with BU Barbell at Cambridge Strength & Conditioning, organized to build community among the powerlifting teams of Massachusetts.",
    dates: "Mar 2023 - Apr 2023",
    organization: "Worcester Polytechnic Institute",
    contributors: ["Abe", "Diyar", "2 others"],
    long: "I corresponded with BU Barbell representatives to organize the lift and worked with the WPI Powerlifting executive board on transportation from Worcester to Boston.",
  },
  {
    id: "powerlifting-empowerment-workshop",
    title: "WPI Powerlifting Feminine Empowerment Workshop",
    track: "misc",
    image: "wpi",
    link: LINKEDIN,
    text: "A panel of nationally ranked feminine-presenting powerlifters, built to welcome newcomers to powerlifting and fitness.",
    dates: "Mar 2023 - Apr 2023",
    organization: "Worcester Polytechnic Institute",
    contributors: ["Giovanni", "Celeste", "2 others"],
  },
];
